version: '3.4'

services:

    nginx-reverseproxy:
        build: 
            context: ./nginx
            dockerfile: local.Dockerfile
        volumes:
            - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        # links:
        #     - marvelweb
        #     - marvel.world
        #     - marvel.heroes
        #     - marvel.villains
        # network_mode: host 

    # reverse-proxy:
    #     image: nginx:1.17.10
    #     container_name: reverse_proxy_demo
    #     depends_on:
    #         - marvelweb
    #         - marvel.heroes
    #         - marvel.villains
    #         - marvel.world
    #     volumes:
    #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #       - 80:80

    marvelweb:
        build: 
            context: ./marvel-world
            dockerfile: Dockerfile
            args:
                - ARG_REACT_APP_MARVEL=http://localhost/api/marvelworld
        ports: 
            - "8080:80"
        # environment:
        #     - API_URL=DEFAULT
        
    #     # depends_on:
    #     #     - marvelbackend
   
    marvel.heroes:
        image: ${DOCKER_REGISTRY-}marvelheroes
        build:
            context: ./marvel
            dockerfile: ./Marvel.Heroes/Dockerfile

    marvel.villains:
        image: ${DOCKER_REGISTRY-}marvelvillains
        build:
            context: ./marvel
            dockerfile: ./Marvel.Villains/Dockerfile

    marvel.world:
        image: ${DOCKER_REGISTRY-}marvelworld
        build:
            context: ./marvel
            dockerfile: ./Marvel.World/Dockerfile
        ports: 
            - "5002:5000"
        environment:
            - ASPNETCORE_URLS=http://*:5000
            - Services__Heroes=http://marvel.heroes
            - Services__Villains=http://marvel.villains